version: "3"

services:
  eureka:
    build: eureka
    ports:
      - "8761:8080"
    networks:
      - middle

  admin:
    build: admin
    ports:
      - "8080:8080"
    networks:
      - middle

  gateway:
    build: gateway
    ports:
      - "8081:8080"
    networks:
      - middle

  comment-1:
    build: comment
    environment:
      RELEASE_VERSION: '1.0.0'
      HOST_NAME: 'comment-1'
    networks:
      - middle

  comment-2:
    build: comment
    environment:
      RELEASE_VERSION: '2.0.0'
      HOST_NAME: 'comment-2'
    networks:
      - middle

  post-1:
    build: post
    environment:
      RELEASE_VERSION: '1.0.0'
      HOST_NAME: 'post-1'
    networks:
      - middle

  post-2:
    build: post
    environment:
      RELEASE_VERSION: '2.0.0'
      HOST_NAME: 'post-2'
    networks:
      - middle

  user-1:
    build: user
    environment:
      RELEASE_VERSION: '1.0.0'
      HOST_NAME: 'user-1'
    networks:
      - middle

  user-2:
    build: user
    environment:
      RELEASE_VERSION: '2.0.0'
      HOST_NAME: 'user-2'
    networks:
      - middle
networks:
  middle: