eureka:
  server:
    enable-self-preservation: false
    wait-time-in-ms-when-sync-empty: 30
  instance:
    health-check-url: http://${eureka.instance.hostname}:8080/actuator/health
    hostname: ${HOST_NAME:eureka}
    metadata-map:
      version: ${RELEASE_VERSION:@release.version@}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8080/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'


logging:
  file:
    max-history: 1
  path: '/tmp'