eureka:
  instance:
    health-check-url: http://${eureka.instance.hostname}:8080/actuator/health
    hostname: ${HOST_NAME:comment}
    metadata-map:
      version: ${RELEASE_VERSION:@release.version@}
  client:
    service-url:
      defaultZone: http://eureka:8080/eureka
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    max-history: 1
  path: '/tmp'
